# Generated by Django 6.1.1 on 2026-09-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_order_product_remove_course_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('recibida', 'Recibida'), ('preparando', 'Preparando'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='recibida', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Accesorios', 'Accesorios'), ('Hogar', 'Hogar')], max_length=80),
        ),
    ]
