# Generated by Django 6.1.1 on 2026-09-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_product_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#2f6042', max_length=7),
        ),
    ]
