# Generated by Django 6.1.1 on 2026-10-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_bus_ruta_remove_product_tenant_remove_profile_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='detalles',
            field=models.JSONField(default=list),
        ),
    ]
